### PR TITLE
Fix rouge path problem

### PR DESCRIPTION
**Pull request by zhangir-azerbayev**

### CODE REVIEW

**Comment by zhangir-azerbayev** [comment]
The current solution only works on unix systems, but I can't even get summ_eval to pip install on my windows machine. So I'm thinking that we merge this branch as is and then open an issue regarding the problems I'm having with windows.

**Review by niansong1996 — COMMENTED** [review]
Generally looks good, but do you still need the first few cells for setting the environment variable? Can you test without it?

**Comment by zhangir-azerbayev** [comment]
@niansong1996 I removed the relevant cells in the demo, and it works.

**Comment by niansong1996** [comment]
Okay, merging this now

**Pull request merged**
