### PR TITLE
Troyfeng116/code styling test

### PR DESCRIPTION
**Pull request by troyfeng116**
- Test linters (`black` and `flake8`) on sample file (see `model/base_model.py` for formatting diffs)
- Add Contributors section to README with guidelines on code styling and linting

### CODE REVIEW

**Comment by niansong1996** [comment]
I see. I think probably a good way is to enable `flake8` and `mpypy` in our CI routine and **output everything as errors**. Then we let people know that we've also configured `black` to fix those automatically, but for static types, docstrings and comments, they would need to fix it themselves. I think it's better than "asking everyone to do xyz" before making the PR, what do you think?

**Comment by troyfeng116** [comment]
> I see. I think probably a good way is to enable `flake8` and `mpypy` in our CI routine and **output everything as errors**. Then we let people know that we've also configured `black` to fix those automatically, but for static types, docstrings and comments, they would need to fix it themselves. I think it's better than "asking everyone to do xyz" before making the PR, what do you think?

Yeah agreed. So for now, to avoid another PR that's way too big, maybe we can do this:
- Merge the GH actions PR first to permanently move to GH actions for CI (just need to do a few more things for that to be ready to merge) and deprecate the Travis CI system, then
- Apply `black` to the entire code base and add basic code styling to the GH actions tests (basically the stuff in this PR), then
- In that PR, change all files to comply with max line length so that the new code styling tests pass, then
- Create a new PR to add static type checking with `mypy` and slowly fix all errors

Lmk what you think

**Comment by troyfeng116** [comment]
After GH actions are merged and these tests and changes are moved to that new system, this PR can be closed.

**Comment by niansong1996** [comment]
I like your plan, let's proceed that way. 

Fixed a minor conflict at my own discretion, please check.

**Pull request closed without merging**
