### PR TITLE
cleanup to prepare for the 0.1 release

### PR DESCRIPTION
**Pull request by niansong1996**
Cleaned up files/dirs that are not touch for 5+ months. 

There are some files that I am not sure whether they can be deleted, for which I will ask people to take a look in the follow-up thread.

### CODE REVIEW

**Comment by niansong1996** [comment]
A list of files I am not sure about:
* @chatc is `.gitmodules` still needed?
* @MuroriM is `SummerTime.egg-info` automatically generated? if so, can we delete this?
* @troyfeng116 why do we need `summertime.py` for building? it seems a bit awkward lying in the top-level folder like that, if it's necessary, can we move it to test or smth? 
* @troyfeng116 @MuroriM can we delete `summertime_pkg`?

**Comment by MuroriM** [comment]
@niansong1996  Most of the files mentioned above `SummerTime.egg-info`, `summertime.py`, `summertime_pkg` are from the previous pip package PR. We should definitely remove them as they are unnecessary right now and might lead to confusion down the line.

But I'd first double-check with @troyfeng116 , on which files are needed for Travis as it might be using some of the files.

To view files from the previous pip efforts, I recommend taking a look at this branch [murori/pip-package](https://github.com/Yale-LILY/SummerTime/tree/murori/pip-package)

**Comment by troyfeng116** [comment]
@niansong1996  The tests don't use `summertime.py`, I do think `download.py` is needed though. `summertime_pkg` can be deleted. And I think `dependencies.txt` has been there for a while now, I don't know why it's there so we can remove it

**Comment by niansong1996** [comment]
@troyfeng116 I had a failed build with commit 7d781fb because of trying to find `summertime.py` that I deleted, then I added it back in f8f3040 and the build passes, do you know why this is?

**Comment by troyfeng116** [comment]
> @troyfeng116 I had a failed build with commit [7d781fb](https://github.com/Yale-LILY/SummerTime/commit/7d781fb9cf1fefe4f54889413b85cae3f6a04966) because of trying to find `summertime.py` that I deleted, then I added it back in [f8f3040](https://github.com/Yale-LILY/SummerTime/commit/f8f30406cb07761e1ab53ed83b6eaf6dbd91904a) and the build passes, do you know why this is?

Looks like it's used in `setup.py`, I guess we can either remove that script or leave it there

**Comment by niansong1996** [comment]
> I do think download.py is needed though.

@troyfeng116 What's the functionality of it? May we move it inside one of the folders?

**Comment by MuroriM** [comment]
I created `setup.py` for the pip package. If it doesn't serve any other purpose, we can delete both `setup.py` and `summertime.py`

**Comment by niansong1996** [comment]
@MuroriM `setup.py` should still be there, but `summertime.py` is included in it as a startup script, which is unnecessary, so I've deleted it in 0fa09ac

**Comment by troyfeng116** [comment]
> @troyfeng116 What's the functionality of it? May we move it inside one of the folders?

Actually looks like it's not needed, we can delete it

**Comment by niansong1996** [comment]
Thanks, @troyfeng116 Btw, do you know why do we need an `__init__.py` at the top level?

**Comment by troyfeng116** [comment]
> Thanks, @troyfeng116 Btw, do you know why do we need an `__init__.py` at the top level?

No that was there way before, maybe to make importing easier for local repos? Not necessary for tests or anything else dev-wise

**Comment by niansong1996** [comment]
> No that was there way before, maybe to make importing easier for local repos? Not necessary for tests or anything else dev-wise

I see, let me try to remove it and if all tests are still passing, probably means that it's useless

**Pull request merged**
