### PR TITLE
troyfeng116/ci-isolation

### PR DESCRIPTION
**Pull request by troyfeng116**

### CODE REVIEW

**Comment by niansong1996** [comment]
@troyfeng116 I guess this is needed now?

**Comment by troyfeng116** [comment]
> @troyfeng116 I guess this is needed now?

Did something else break? I see `main` is building. Originally I made this PR to try to fix the non-concurrency issue, but it didn't work. I can revisit later though

**Comment by niansong1996** [comment]
Ah, sorry, I mean "I guess this is \*not\* needed now"?

**Comment by troyfeng116** [comment]
> Ah, sorry, I mean "I guess this is *not* needed now"?

Yes, we can close the PR (but keep branch) for now. Sorry

**Comment by niansong1996** [comment]
Great, thanks!

**Pull request closed without merging**
