### PR TITLE
troyfeng116/travis-ci

### PR DESCRIPTION
**Pull request by troyfeng116**
- Travis CI GH integration

### CODE REVIEW

**Comment by niansong1996** [comment]
Great job on this, btw, why does it have two jobs (PR build and branch build)? Aren't they the same thing? Moreover, have you made changes to switch to only one python version?

**Comment by niansong1996** [comment]
What's the current status on this, is it ready to be merge?

**Comment by troyfeng116** [comment]
> What's the current status on this, is it ready to be merge?

Yep, I think it is. However, builds will not be triggered on `main` (since branch builds are off right now), so unless other open PRs rebase onto `main` after this one is merged, they could break the build

**Comment by niansong1996** [comment]
@troyfeng116 Why do we need `openmpi` tho?

**Comment by troyfeng116** [comment]
> @troyfeng116 Why do we need `openmpi` tho?

I think it was a dependency for an HMNet eval module. Needs to be in `requirements.txt`, so need a few setup steps for it to be installed on Travis

**Comment by niansong1996** [comment]
@troyfeng116  I see that it's currently passing on Travis and the code LGTM. Is it up for merging into main?

**Comment by troyfeng116** [comment]
> @troyfeng116 I see that it's currently passing on Travis and the code LGTM. Is it up for merging into main?

Yep, we should be good to merge into main. We can look into custom CI servers and cleanup afterwards?

**Comment by niansong1996** [comment]
Sounds good to me, merging it now

**Pull request merged**
