### PR TITLE
Added meteor metric

### PR DESCRIPTION
**Pull request by zhangir-azerbayev**

### CODE REVIEW

**Comment by niansong1996** [comment]
Isn't METEOR available in SummEval as well, any particular reason that we are not using them? (but it's okay if the current version works

**Comment by zhangir-azerbayev** [comment]
@niansong1996 I chose not to use the SummEval version because it depends on having Java installed.

**Comment by niansong1996** [comment]
I see, then this is a reasonable solution.

**Comment by niansong1996** [comment]
@zhangir-azerbayev Can you add a test case for this metric?

**Comment by zhangir-azerbayev** [comment]
@niansong1996 The evaluation unit test automatically tests every metric in `SUPPORTED_EVALUATION_METRICS`. Is this what you mean?

**Comment by niansong1996** [comment]
I see, then have this passed the tests?

**Comment by zhangir-azerbayev** [comment]
@niansong1996 After Troy's fixes to the script we discussed in the previous meeting, the tests will pass.

**Comment by niansong1996** [comment]
Okay then, let me merge this for now

**Pull request merged**
