### PR TITLE
Specify cache location for single dataset

### PR DESCRIPTION
**Pull request by MuroriM**
Adds the ability to specify the location to download the dataset to or load it from

### CODE REVIEW

**Comment by MuroriM** [comment]
Addresses #77, allowing users to specify where to store/load a dataset

**Comment by niansong1996** [comment]
LGTM. But have you written tests for them?

**Review by niansong1996 — COMMENTED** [review]
Looks good, but maybe adding tests to it?

**Comment by MuroriM** [comment]
Will add tests. Once done, it should also take care of #49

**Pull request merged**
